# GitLab CI/CD Pipeline Configuration

# Global environment variables
variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/library_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  POSTGRES_DB: "library_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_LIQUIBASE_ENABLED: "true"

stages:
  - build
  - test

# Build Job
build-job:
  stage: build
  image: azul/zulu-openjdk:17
  script:
    - echo "Setting executable permission for gradlew"
    - chmod +x ./gradlew
    - echo "Building the application..."
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/
    when: always

# Test Job with PostgreSQL
unit-test-job:
  stage: test
  image: azul/zulu-openjdk:17
  services:
    - name: postgres:14
      alias: postgres
  script:
    - echo "Waiting for PostgreSQL to initialize..."
    - sleep 20  # Wait to ensure DB is ready
    - echo "Running unit tests..."
    - ./gradlew test --no-daemon
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    when: always
