stages:
  - build
  - test

# Build Job
build-job:
  stage: build
  image: openjdk:17  
  script:
    - echo "Starting build for Library Management System..."
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/
    when: always

# Unit Test Job
unit-test-job:
  stage: test
  image: openjdk:17
  script:
    - echo "Running unit tests..."
    - ./gradlew test --no-daemon
    - echo "All unit tests passed successfully!"
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    when: always
