services:
  - name: postgres:14
    alias: postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/library_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"

stages:
  - build
  - test

build-job:
  stage: build
  image: azul/zulu-openjdk:17
  script:
    - chmod +x ./gradlew
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/

unit-test-job:
  stage: test
  image: azul/zulu-openjdk:17
  script:
    - ./gradlew test --no-daemon
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
