stages:
  - build
  - test

# Build Job
build-job:
  stage: build
  image: azul/zulu-openjdk:17 
  script:
    - echo "Starting build for Library Management System..."
    - chmod +x ./gradlew  
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/
    when: always

# Unit Test Job
unit-test-job:
  stage: test
  image: azul/zulu-openjdk:17
  script:
    - echo "Running unit tests for Library Management System..."
    - chmod +x ./gradlew
    - ./gradlew test --no-daemon
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
    when: always
