services:
  - name: postgres:14
    alias: postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

variables:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/library_db"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_LIQUIBASE_ENABLED: false  # Optional: Disable Liquibase for tests

stages:
  - build
  - test

build-job:
  stage: build
  image: azul/zulu-openjdk:17
  script:
    - echo "Ensuring Gradle wrapper is executable"
    - chmod +x ./gradlew
    - echo "Building the application"
    - ./gradlew clean build --no-daemon
  artifacts:
    paths:
      - build/libs/

unit-test-job:
  stage: test
  image: azul/zulu-openjdk:17
  script:
    - echo "Waiting for PostgreSQL to be ready..."
    - sleep 20  
    - echo "Running unit tests"
    - ./gradlew test --no-daemon
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
