name: Build & Deploy Lms


on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy Library management System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run tests
        run: ./gradlew test

      - name: Build App
        run:
          gradle clean
          ./gradlew build

#      - name: Login in to Docker Hub
#        run: docker/login-actionv@4
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Push Docker image
#        uses: docker/build-push-action@v4
#        with:
#            context: .
#            file: docker-compose
#            push: true
#            tags: your-dockerhub-username/your-image-name:latest