name: Build & Deploy Lms


on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy Library management System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Run tests
        run: ./gradlew test

      - name: Build App
        run: |
          ./gradlew clean
          ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: muradsharifzada/lms-app:1.0
